"""Initial migration

Revision ID: 390aec43effe
Revises:
Create Date: 2025-10-29 23:28:11.002450+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "390aec43effe"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "spacecraft",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("registry_code", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("manufacturer", sa.String(length=255), nullable=True),
        sa.Column("crew_capacity", sa.Integer(), nullable=True),
        sa.Column("max_delta_v", sa.Integer(), nullable=True),
        sa.Column("operational", sa.Boolean(), nullable=True),
        sa.Column("first_flight_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_spacecraft_id"), "spacecraft", ["id"], unique=False)
    op.create_index(
        op.f("ix_spacecraft_registry_code"),
        "spacecraft",
        ["registry_code"],
        unique=True,
    )
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_spacecraft_registry_code"), table_name="spacecraft")
    op.drop_index(op.f("ix_spacecraft_id"), table_name="spacecraft")
    op.drop_table("spacecraft")
    # ### end Alembic commands ###
    # ### end Alembic commands ###
