name: Build Documentation

on:
  push:
    # Run on main and this specific docs feature branch while debugging here
    branches: [ main, 'ci/docs-fix-autodoc' ]
  pull_request:
    branches: [ main, 'ci/docs-fix-autodoc' ]
  # Allow manual runs from the Actions UI for debugging/validation
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    env:
      DB_HOST: dummy
      DB_PORT: 3306
      DB_USER: dummy
      DB_PASSWORD: dummy
      DB_NAME: dummy
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # install uv and sync (project uses uv/rye for dependency management)
          pip install uv
          uv sync
          # Install project extras for building docs (centralized in pyproject.toml)
          # Install the package in editable mode so Sphinx autodoc can import 'app'
          python -m pip install -e ".[docs]"
          # Also export PYTHONPATH to src as a fallback
          echo "PYTHONPATH=$PWD/src" >> $GITHUB_ENV

      - name: Debug python import/path (CI)
        run: |
          python - <<'PY'
          import sys, importlib.util
          print('PYTHONPATH from environment:', sys.path[0:5])
          print('Full sys.path:')
          for p in sys.path:
              print(' -', p)
          print('\nChecking importability of key modules:')
          for mod in ('app', 'app.api', 'app.api.v1.spacecraft', 'app.services.spacecraft_service'):
              spec = importlib.util.find_spec(mod)
              print(mod, '->', 'FOUND' if spec else 'MISSING')
          PY
      - name: Build Sphinx Documentation
        run: sphinx-build -b html docs/source docs/build -W
