name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    services:
      db:
        image: mariadb:11
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: outer_ring_test
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mariadb-admin ping -h localhost -u root -prootpassword"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install uv
          uv sync
      - name: Run Integration Tests
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_NAME: outer_ring_test
          DB_USER: user
          DB_PASSWORD: password
          DB_ROOT_PASSWORD: rootpassword
          PYTHONPATH: .
        run: pytest tests/integration
