name: CI — Tests & Coverage

on:
  push:
    # Run on main and any ci/* branches so CI fixes can be validated on feature branches
    branches: [ main, 'ci/**' ]
  pull_request:
    branches: [ main, 'ci/**' ]
  # Allow manual runs from the Actions UI (handy for debugging CI on feature branches)
  workflow_dispatch:

jobs:
  unit:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install uv
          uv sync
          # Install development dependencies (pytest, pytest-cov, etc.) so tests can run
          uv pip install --system ".[dev]"
      # Note: unit tests don't require a database service in CI. If you need a DB for
      # unit tests, add a `services` block to this job similar to the `integration` job.
      # The previous explicit wait-for-DB step was removed because there is no DB
      # service configured for the `unit` job and it caused connection refused errors.
      - name: Run unit tests (produce coverage files)
        env:
          COVERAGE_FILE: .coverage.unit
          # Provide DB env vars so Settings() can initialize during imports in CI
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_USER: user
          DB_PASSWORD: password
          DB_NAME: outer_ring
        run: |
          pytest --cov=src --cov-report=xml:coverage-unit.xml tests/unit
      - name: Upload unit coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-unit
          path: |
            .coverage.unit
            coverage-unit.xml

  integration:
    name: Integration tests
    runs-on: ubuntu-latest
    services:
      db:
        image: mariadb:11
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: outer_ring_test
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mariadb-admin ping -h localhost -u root -prootpassword"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install uv
          uv sync
          # Install development dependencies (pytest, pytest-cov, httpx, etc.)
          uv pip install --system ".[dev]"
      - name: Run DB migrations
        run: alembic upgrade head
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_NAME: outer_ring_test
          DB_USER: user
          DB_PASSWORD: password
          DB_ROOT_PASSWORD: rootpassword
          PYTHONPATH: .
      - name: Run integration tests (produce coverage files)
        env:
          COVERAGE_FILE: .coverage.integration
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_NAME: outer_ring_test
          DB_USER: user
          DB_PASSWORD: password
          DB_ROOT_PASSWORD: rootpassword
          PYTHONPATH: .
        run: |
          pytest --cov=src --cov-report=xml:coverage-integration.xml tests/integration
      - name: Upload integration coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-integration
          path: |
            .coverage.integration
            coverage-integration.xml

  combine-and-upload:
    name: Combine coverage and upload
    runs-on: ubuntu-latest
    needs: [unit, integration]
    steps:
      - uses: actions/checkout@v3
      - name: Download unit coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage-unit
          path: artifacts/unit
      - name: Download integration coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage-integration
          path: artifacts/integration
      - name: Upload coverage XMLs to Codecov
        # We upload the XML reports directly (generated by pytest-cov). This is
        # more robust: some jobs produce XML but not a .coverage file, so trying
        # to move/merge .coverage files can fail. Codecov accepts multiple XML
        # reports, so pass the glob for the downloaded artifacts.
        uses: codecov/codecov-action@v4
        with:
          files: artifacts/**/coverage-*.xml
          fail_ci_if_error: true
